bugtracker/urls.py
from django.contrib import admin
from django.urls import path
from tracker.urls import urlpatterns as bugtracker_urls

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += bugtracker_urls

tracker/urls.py
from django.urls import path
from tracker import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.loginview, name='login'),
    path('logout/', views.logoutview, name='logout'),
    path('add_user.html', views.add_user, name='add_user'),
    path('user/<int:id>', views.user, name='user'),
    path('ticket/<int:id>', views.ticket, name='ticket'),
    path('add_ticket.html', views.add_ticket, name='add_ticket'),
    path('edit_ticket/<int:id>', views.ticket_edit, name='edit_ticket'),
]

tracker/models.py
from django.db import models
from django.conf import settings
from datetime import datetime

from django.contrib.auth.models import AbstractUser

# Create your models here.
class MyUser(AbstractUser):
    display_name = models.CharField(max_length=50, null=True, blank=True)

class Ticket(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    filed_by = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='filed_by')
    assigned_to = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='assigned_to', null=True, blank=True, default=None)
    completed_by = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='completed_by', null = True, blank = True, default=None)

    # https://stackoverflow.com/questions/2771676/django-datetime-issues-default-datetime-now
    time_submitted = models.DateTimeField(default=datetime.now)

    new = 'n'
    inprog = 'p'
    done = 'd'
    invalid = 'na'

    status_choices = {
        (new, 'New'),
        (inprog, 'In-Progress'),
        (done, 'Done'),
        (invalid, 'Invalid'),
    }

    ticket_status = models.CharField(
        max_length=10,
        choices=status_choices,
        default=new,
    )

    def __str__(self):
        return self.title

tracker/forms.py
from django import forms
from django.forms import modelform_factory
from django.contrib.auth.forms import UserCreationForm
from tracker.models import Ticket, MyUser

AddTicketForm = modelform_factory(Ticket, exclude=['assigned_to', 'completed_by'])

EditTicketForm = modelform_factory(Ticket, exclude=['filed_by'])

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(widget=forms.PasswordInput)

class AddUserForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ('first_name', 'last_name', 'display_name', 
                  'username', 'password1', 'password2')

tracker/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect, reverse, HttpResponseRedirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from tracker.forms import AddTicketForm, LoginForm, AddUserForm, EditTicketForm
from tracker.models import Ticket, MyUser

# Create your views here.
@login_required
def home(request):
    n_tickets = Ticket.objects.filter(ticket_status='n')
    ip_tickets = Ticket.objects.filter(ticket_status='p')
    d_tickets = Ticket.objects.filter(ticket_status='d')
    na_tickets = Ticket.objects.filter(ticket_status='na')
    return render(request, 'home.html',
                  {'n_tickets': n_tickets,
                  'ip_tickets': ip_tickets,
                  'd_tickets': d_tickets,
                  'na_tickets': na_tickets})

@login_required
def ticket(request, id):
    ticket = get_object_or_404(Ticket, pk=id)
    return render(request, 'ticket.html', {'ticket': ticket})

@login_required
def add_user(request):
    if request.method == 'POST':
        form = AddUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = AddUserForm()
    return render(request, 'generic_form.html', {'form': form})

@login_required
def user(request, id):
    user = get_object_or_404(MyUser, pk=id)
    # Got help from Peter on 5/7 for redering and sorting recipes
    a_tickets = Ticket.objects.filter(assigned_to=user)
    f_tickets = Ticket.objects.filter(filed_by=user)
    c_tickets = Ticket.objects.filter(completed_by=user)
    return render(request, 'user.html', {'user': user, 
                                        'a_tickets': a_tickets,
                                        'c_tickets': c_tickets,
                                        'f_tickets': f_tickets})

def loginview(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                request, username=data['username'], password=data['password']
                )
            if user:
                login(request, user)
                return HttpResponseRedirect(
                    request.GET.get('next', reverse('home'))
                )
    form = LoginForm()
    return render(request, 'generic_form.html', {'form': form})

def logoutview(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return HttpResponseRedirect(
                    request.GET.get('next', reverse('home'))
                )

@login_required
def add_ticket(request):
    if request.method == 'POST':
        form = AddTicketForm(request.POST)
        if form.is_valid():
            ticket = form.save()
            ticket.refresh_from_db()
            id = ticket.id
            return HttpResponseRedirect(reverse('ticket', args=(id,)))
    else:
        form = AddTicketForm()
    return render(request, 'generic_form.html', {'form': form})

@login_required
def ticket_edit(request, id):
    ticket = get_object_or_404(Ticket, pk=id)
    if request.method == "POST":
        form = EditTicketForm(request.POST, instance=ticket)
        form.save()
        if form.cleaned_data['assigned_to'] != None:
            ticket.ticket_status = 'p'
            ticket.completed_by = None
            ticket.assigned_to = form.cleaned_data['assigned_to']
            ticket.save()
        form_status = form.cleaned_data['ticket_status']
        if form_status == 'na':
            ticket.completed_by = None
            ticket.assigned_to = None
            ticket.save()
        if form_status == 'd':
            ticket.ticket_status = 'd'
            ticket.completed_by = form.cleaned_data['assigned_to']
            ticket.assigned_to = None
            ticket.save()
        return HttpResponseRedirect(reverse('ticket', args=(id,)))

    form = EditTicketForm(instance=ticket)
    return render(request, 'generic_form.html', {'form': form})

tracker/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

tracker/templates/generic_form.html
<form action="" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit!">
</form>
<br>
<a href="{% url 'home' %}">Back Home</a>

tracker/templates/home.html
{% extends "base.html" %}

{% block title %}Bug Tracker{% endblock %}


{% block content %}

    <h1>Welcome to the Bug Tracker!</h1>
    
    <h3>New Tickets:</h3>
    <ul>
        {% for ticket in n_tickets %}
            <li>
                <a href="{% url 'ticket' ticket.id %}">
                    {{ ticket }}
                </a>
            </li>
        {% endfor %}
    </ul>

    <h3>In-Progress Tickets:</h3>
    <ul>
        {% for ticket in ip_tickets %}
            <li>
                <a href="{% url 'ticket' ticket.id %}">
                    {{ ticket }}
                </a>
            </li>
        {% endfor %}
    </ul>

    <h3>Completed:</h3>
    <ul>
        {% for ticket in d_tickets %}
            <li>
                <a href="{% url 'ticket' ticket.id %}">
                    {{ ticket }}
                </a>
            </li>
        {% endfor %}
    </ul>

    <h3>Invalid Tickets:</h3>
    <ul>
        {% for ticket in na_tickets %}
            <li>
                <a href="{% url 'ticket' ticket.id %}">
                    {{ ticket }}
                </a>
            </li>
        {% endfor %}
    </ul>

    <br>
    <p>You are currently logged in: {{user.is_authenticated}}</p>
    <br>
    <a href="{% url 'add_ticket' %}">
        Add New Ticket
    </a>
    <br>
    <a href="{% url 'add_user' %}">
        Setup New User
    </a>
    <br>
    <a href="{% url 'user' user.id %}">
        My Profile
    </a>
    <br>
    <a href="{% url 'login' %}">
        Login
     </a>
    <br>
    <a href="{% url 'logout' %}">
        Logout
     </a>
     

{% endblock %}

tracker/templates/ticket.html
{% extends "base.html" %}

{% block title %}Ticket Info{% endblock %}

{% block content %}
    <h1>{{ticket.title}}</h1>
    <h2>Ticket Status:  {{ticket.get_ticket_status_display}}</h2>
    <h3>Description</h3>
    <p> {{ticket.description}}</p>
    <p>Submitted by: <a href="{% url 'user' ticket.filed_by.id %}"> {{ticket.filed_by}}</a></p>
    <p>Assigned To:  {{ticket.assigned_to}}</p>
    <p>Completed By:  {{ticket.completed_by}}</p>
    <p>Time Submitted: {{ticket.time_submitted}}</p>

    

    <a href="{% url 'home' %}">Back Home</a>
    <br>
    <a href="{% url 'edit_ticket' ticket.id %}">Edit Ticket</a>
    
{% endblock %}

tracker/templates/user.html
{% extends "base.html" %}

{% block title %}User Info{% endblock %}

{% block content %}

    <h1>{{user}}</h1>

    <h3>Currently Assinged:</h3>
    <ul>
        {% for ticket in a_tickets %}
            <li>
                <a href="{% url 'ticket' ticket.id %}">
                    {{ ticket }}
                </a>
            </li>
        {% endfor %}
    </ul>

    <h3>Tickets Submitted:</h3>
    <ul>
        {% for ticket in f_tickets %}
            <li>
                <a href="{% url 'ticket' ticket.id %}">
                    {{ ticket }}
                </a>
            </li>
        {% endfor %}
    </ul>

    <h3>Completed:</h3>
    <ul>
        {% for ticket in c_tickets %}
            <li>
                <a href="{% url 'ticket' ticket.id %}">
                    {{ ticket }}
                </a>
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'home' %}">Back Home</a>
    
{% endblock %}